### ISSUE TITLE
Settings are overwritten when projects are open in multiple windows

### ISSUE THREAD

**Issue by staffanf** [krasa/EclipseCodeFormatter#141]
I typically use IntelliJ with a number of separate projects open in different windows.
Each of these use version controlled settings for code formatting, some of which have differing relative paths.
If I change the settings for one open project, then the settings for all other open projects are also changed i.e. the .idea/misc.xml in projectB modified if I change the settings in projectA.

**Comment by krasa** [comment]
Create a new profile.

**Comment by staffanf** [comment]
OK, now I see... Been using this for a couple of years and not figured that out.
Normally in IntelliJ when it says "For current project" at the top of the settings page, then those setting are not global. This kinda goes against that convention.

**Comment by krasa** [comment]
yep, for legacy reasons ;-)

**Comment by markiewb** [comment]
I saw this https://github.com/krasa/EclipseCodeFormatter/blob/039b9cc98154e04b98ce187e704157a61a6f8adc/src/java/krasa/formatter/settings/MyConfigurable.java#L66 But I guess this is only the tip of the legacy iceberg

**Comment by krasa** [comment]
It looks worse than it is :)

Perhaps I could fix it by this:

![image](https://cloud.githubusercontent.com/assets/1160875/26747469/456b256c-47f6-11e7-9c69-21c73da1b3b5.png)



Or an option to not use profiles:
![image](https://cloud.githubusercontent.com/assets/1160875/26747439/1467a03a-47f6-11e7-9607-d19c0fefcefc.png)

**Comment by staffanf** [comment]
I think the second one would be pretty understandable. In my case the the global option is not what I'd expect and using it should really be opt-in.

**Comment by markiewb** [comment]
Yes, the second alternative looks more reasonable because the user has the
choice.

Instead of creating a new checkbox consider to integrate such a global
profile into the existing combo box. And make this global profile
non-erasable.

Den 5 juni 2017 09:53 skrev "Staffan Forsell" <notifications@github.com>:

**Comment by krasa** [comment]
You mean adding a non-erasable 'Project specific' profile into the combo box?

**Comment by markiewb** [comment]
![2017-06-05_18h34_59](https://cloud.githubusercontent.com/assets/1857095/26793331/e54f92f6-4a1d-11e7-8a6a-410b833358e9.png)
No, instead of the checkbox add a non-eraseable "global" profile to the combobox. 
When the "global" profile is selected the buttons Rename, Copy, Delete are disabled. Does it make sense?

**Comment by krasa** [comment]
Well, no. 
I don't know what you mean by that global profile. All profiles are currently global - meaning that they are synchronized across projects and their settings is persisted in .IntelliJIdea2017.2\config\options - an update in one project will override settings in other projects which have selected the same profile.

So if that one non-erasable is global, are others project specific - so that they will not be visible across projects?

**Comment by markiewb** [comment]
Yes. That makes sense. Thanks for the explanation. Project specific
profiles are only available for the specific project. But what is the use
case then? I guess you only seldom switch between profiles within one
project.

So I go for the first variant "make the user aware that he/she changes the
profile for other projects too". Profiles are global and can be referred to
in projects.

Den 5 juni 2017 19:07 skrev "Vojtěch Krása" <notifications@github.com>:

**Comment by krasa** [comment]
IJ 2017 has it finally done nicely:
![image](https://cloud.githubusercontent.com/assets/1160875/26808715/20befc64-4a5f-11e7-8426-51d4075332c4.png)
Project specific profile could be actually more user friendly.  Less clicking when setting up a new project with a different config. 

Also. duplication of data in IDE and project config file confuses people, due to path macros  ($PROJECT_DIR$) which are automatically managed by Intelli -> https://github.com/krasa/EclipseCodeFormatter/issues/116
Having an option to use a non-confusing profile is a solution. :-)

**Comment by krasa** [comment]
Does anyone want to try it? https://github.com/krasa/EclipseCodeFormatter/releases/tag/17.0.132.637.0
